export type Language = 'ch' | 'en';

export const translations = {
  en: {
    appTitle: "POE Filter Editor",
    editor: "Editor",
    simulator: "Simulator",
    saveExport: "Save & Export",
    saveConfig: "Save Config",
    generateFilter: "Generate Filter",
    selectFile: "Select a file from the sidebar to edit",
    itemsInTier: "Items in this Tier",
    noItems: "No items in this tier",
    searchPlaceholder: "Search to add item...",
    filterPlaceholder: "Filter current items...",
    fontSize: "Font Size",
    textColor: "Text Color",
    borderColor: "Border Color",
    bgColor: "BG Color",
    itemPreview: "Item Preview",
    dropSimulator: "Drop Simulator",
    visual: "Visual",
    rawText: "Raw Text",
    clearGround: "Clear Ground",
    refreshStyles: "Refresh Styles",
    typeToDrop: "Type item name to drop...",
    groundEmpty: "Ground is empty. Add some items!",
    loading: "Loading...",
    generating: "Generating...",
    generatedSuccess: "Filter generated successfully!",
    saveSuccess: "Saved successfully!",
    moveFailed: "Failed to move item",
    loadFailed: "Failed to load",
    inspector: "Inspector",
    rawFilter: "Raw Filter Code",
    styleClipboard: "Style Clipboard",
    copyStyle: "Copy Style",
    pasteStyle: "Paste Style",
    clearClipboard: "Clear",
    visibility: "Visibility",
    show: "Show",
    hide: "Hide",
    gameVersion: "Game Version",
    gameMode: "Game Mode",
    normalMode: "Normal",
    ruthlessMode: "Ruthless",
    rules: "Rules",
    addRule: "Add Rule",
    deleteRule: "Delete Rule",
    targets: "Targets",
    conditions: "Conditions",
    overrides: "Overrides",
    comment: "Comment",
    sound: "Sound",
    icon: "Icon",
    beam: "Beam",
    text: "Text",
    border: "Border",
    background: "Background",
    transparency: "Transparency",
    coast: "Coast",
    forest: "Forest",
    sand: "Sand",
    volume: "Volume",
    soundType: "Sound Type",
    default: "Default",
    sharket: "Sharket",
    custom: "Custom",
    filePath: "File Path",
    test: "Test",
    search: "Search...",
    size: "Size",
    shape: "Shape",
    temporary: "Temporary",
    small: "Small",
    medium: "Medium",
    large: "Large",
    small_sh: "S",
    medium_sh: "M",
    large_sh: "L",
    copy: "Copy",
    paste: "Paste",
    cancel: "Cancel",
    ok: "OK",
    none: "None",
    permanent: "Permanent",
    viewerSettings: "Viewer Settings",
    copyText: "Copy Text",
    bulkEdit: "Bulk Edit",
    addNewTier: "Add New Tier",
    testSound: "Test Sound",
    color: "Color",
    name: "Name",
    source: "Source",
    targetTooltip: "Targets are optional. If empty, the rule applies to all items in this tier. Use targets to apply specific conditions or style overrides to individual items within the tier.",
    Red: "Red",
    Green: "Green",
    Blue: "Blue",
    Brown: "Brown",
    White: "White",
    Yellow: "Yellow",
    Cyan: "Cyan",
    Grey: "Grey",
    Orange: "Orange",
    Pink: "Pink",
    Purple: "Purple",
    Temp:"Temp",
  },
  ch: {
    appTitle: "POE 过滤器编辑器",
    editor: "编辑器",
    simulator: "模拟器",
    saveExport: "保存与导出",
    saveConfig: "保存配置",
    generateFilter: "生成过滤器",
    selectFile: "从左侧选择文件以编辑",
    itemsInTier: "此阶级物品",
    noItems: "此阶级无物品",
    searchPlaceholder: "搜索以添加物品...",
    filterPlaceholder: "筛选当前物品...",
    fontSize: "字体大小",
    textColor: "文本颜色",
    borderColor: "边框颜色",
    bgColor: "背景颜色",
    itemPreview: "物品预览",
    dropSimulator: "掉落模拟器",
    visual: "可视化",
    rawText: "原始文本",
    clearGround: "清空地面",
    refreshStyles: "刷新样式",
    typeToDrop: "输入物品名称以落...",
    groundEmpty: "地面为空。添加一些掉落物吧~",
    loading: "加载中...",
    generating: "生成中...",
    generatedSuccess: "过滤器生成成功！",
    saveSuccess: "保存成功！",
    moveFailed: "移动物品失败",
    loadFailed: "加载失败",
    inspector: "检查员",
    rawFilter: "原始过滤器代码",
    styleClipboard: "样式剪贴板",
    copyStyle: "复制样式",
    pasteStyle: "粘贴样式",
    clearClipboard: "清空",
    visibility: "可见性",
    show: "显示",
    hide: "隐藏",
    gameVersion: "游戏版本",
    gameMode: "游戏模式",
    normalMode: "普通",
    ruthlessMode: "无情",
    rules: "规则",
    addRule: "添加规则",
    deleteRule: "删除规则",
    targets: "目标",
    conditions: "条件",
    overrides: "覆盖设定",
    comment: "备注",
    sound: "声音",
    icon: "图标",
    beam: "光柱",
    text: "文本",
    border: "边框",
    background: "背景",
    transparency: "透明度",
    coast: "海滩",
    forest: "丛林",
    sand: "沙漠",
    volume: "音量",
    soundType: "声音类型",
    default: "系统默认",
    sharket: "Sharket音效",
    custom: "自定义路径",
    filePath: "文件路径",
    test: "测试",
    search: "搜索...",
    size: "大小",
    shape: "形状",
    temporary: "临时",
    small: "小",
    medium: "中",
    large: "大",
    small_sh: "小",
    medium_sh: "中",
    large_sh: "大",
    copy: "复制",
    paste: "粘贴",
    cancel: "取消",
    ok: "确定",
    none: "无",
    permanent: "永久",
    viewerSettings: "显示设置",
    copyText: "复制文本",
    bulkEdit: "批量编辑",
    addNewTier: "添加新阶级",
    testSound: "测试音效",
    color: "颜色",
    targetTooltip: "目标是可选的。如果为空，则该规则应用于此阶级中的所有物品。使用目标可以对阶级内的单个物品应用特定条件或样式覆盖。",
    Red: "红色",
    Green: "绿色",
    Blue: "蓝色",
    Brown: "棕色",
    White: "白色",
    Yellow: "黄色",
    Cyan: "青色",
    Grey: "灰色",
    Orange: "橙色",
    Pink: "粉色",
    Purple: "紫色",
    Temp:"临时",
  }
};

export const useTranslation = (lang: Language) => {

  return translations[lang];

};



export const getItemName = (item: { name: string; name_ch?: string }, lang: Language) => {

  if (lang === 'ch' && item.name_ch) return item.name_ch;

  return item.name;

};
