export type Language = 'ch' | 'en';

export const translations = {
  en: {
    appTitle: "POE Filter Editor",
    editor: "Editor",
    simulator: "Simulator",
    saveExport: "Save & Export",
    saveConfig: "Save Config",
    generateFilter: "Generate Filter",
    selectFile: "Select a file from the sidebar to edit",
    itemsInTier: "Items in this Tier",
    noItems: "No items in this tier",
    searchPlaceholder: "Search to add item...",
    filterPlaceholder: "Filter current items...",
    fontSize: "Font Size",
    textColor: "Text Color",
    borderColor: "Border Color",
    bgColor: "BG Color",
    itemPreview: "Item Preview",
    dropSimulator: "Drop Simulator",
    visual: "Visual",
    rawText: "Raw Text",
    clearGround: "Clear Ground",
    refreshStyles: "Refresh Styles",
    typeToDrop: "Type item name to drop...",
    groundEmpty: "Ground is empty. Drop some items!",
    loading: "Loading...",
    generating: "Generating...",
    generatedSuccess: "Filter generated successfully!",
    saveSuccess: "Saved successfully!",
    moveFailed: "Failed to move item",
    loadFailed: "Failed to load",
    visibility: "Visibility",
    show: "Show",
    hide: "Hide (Minimal)",
    rules: "Rules",
    addRule: "Add Rule",
    deleteRule: "Delete Rule",
    targets: "Targets",
    conditions: "Conditions",
    overrides: "Overrides",
    comment: "Comment",
  },
  ch: {
    appTitle: "POE 过滤器编辑器",
    editor: "编辑器",
    simulator: "模拟器",
    saveExport: "保存与导出",
    saveConfig: "保存配置",
    generateFilter: "生成过滤器",
    selectFile: "从左侧选择文件以编辑",
    itemsInTier: "此阶级物品",
    noItems: "此阶级无物品",
    searchPlaceholder: "搜索以添加物品...",
    filterPlaceholder: "筛选当前物品...",
    fontSize: "字体大小",
    textColor: "文本颜色",
    borderColor: "边框颜色",
    bgColor: "背景颜色",
    itemPreview: "物品预览",
    dropSimulator: "掉落模拟器",
    visual: "可视化",
    rawText: "原始文本",
    clearGround: "清空地面",
    refreshStyles: "刷新样式",
    typeToDrop: "输入物品名称以掉落...",
    groundEmpty: "地面为空。掉落一些物品吧！",
    loading: "加载中...",
    generating: "生成中...",
    generatedSuccess: "过滤器生成成功！",
    saveSuccess: "保存成功！",
    moveFailed: "移动物品失败",
    loadFailed: "加载失败",
    rules: "规则",
    addRule: "添加规则",
    deleteRule: "删除规则",
    targets: "目标",
    conditions: "条件",
    overrides: "覆盖设定",
    comment: "备注",
  }
};

export const useTranslation = (lang: Language) => {
  return translations[lang];
};
