export type Language = 'ch' | 'en';

export const CLASS_KEY_MAP: Record<string, string> = {
    "Stackable Currency": "Stackable_Currency",
    "Body Armours": "Body_Armours",
    "Boots": "Boots",
    "Gloves": "Gloves",
    "Helmets": "Helmets",
    "Shields": "Shields",
    "One Hand Axes": "One_Hand_Axes",
    "One Hand Maces": "One_Hand_Maces",
    "One Hand Swords": "One_Hand_Swords",
    "Sceptres": "Sceptres",
    "Staves": "Staves",
    "Warstaves": "Warstaves",
    "Two Hand Axes": "Two_Hand_Axes",
    "Two Hand Maces": "Two_Hand_Maces",
    "Two Hand Swords": "Two_Hand_Swords",
    "Wands": "Wands",
    "Active Skill Gems": "Active_Skill_Gems",
    "Support Skill Gems": "Support_Skill_Gems",
    "Maps": "Maps",
    "Map Fragments": "Map_Fragments",
    "Divination Card": "Divination_Card",
    "Amulets": "Amulets",
    "Rings": "Rings",
    "Belts": "Belts",
    "Bows": "Bows",
    "Claws": "Claws",
    "Daggers": "Daggers",
    "Rune Daggers": "Rune_Daggers",
    "Quivers": "Quivers"
};

export const translations = {
  en: {
    appTitle: "POE Filter Editor",
    editor: "Editor",
    simulator: "Simulator",
    saveExport: "Save & Export",
    saveConfig: "Save Config",
    generateFilter: "Generate Filter",
    selectFile: "Select a file from the sidebar to edit",
    itemsInTier: "Items in this Tier",
    noItems: "No items in this tier",
    searchPlaceholder: "Search to add item...",
    filterPlaceholder: "Filter current items...",
    fontSize: "Font Size",
    textColor: "Text Color",
    borderColor: "Border Color",
    bgColor: "BG Color",
    itemPreview: "Item Preview",
    dropSimulator: "Drop Simulator",
    visual: "Visual",
    rawText: "Raw Text",
    clearGround: "Clear Ground",
    refreshStyles: "Refresh Styles",
    typeToDrop: "Type item name to drop...",
    groundEmpty: "Ground is empty. Add some items!",
    loading: "Loading...",
    generating: "Generating...",
    generatedSuccess: "Filter generated successfully!",
    saveSuccess: "Saved successfully!",
    moveFailed: "Failed to move item",
    loadFailed: "Failed to load",
    inspector: "Inspector",
    rawFilter: "Raw Filter Code",
    styleClipboard: "Style Clipboard",
    copyStyle: "Copy Style",
    pasteStyle: "Paste Style",
    clearClipboard: "Clear",
    visibility: "Visibility",
    show: "Show",
    hide: "Hide",
    gameVersion: "Game Version",
    gameMode: "Game Mode",
    normalMode: "Normal",
    ruthlessMode: "Ruthless",
    rules: "Rules",
    addRule: "Add Rule",
    deleteRule: "Delete Rule",
    targets: "Targets",
    conditions: "Conditions",
    overrides: "Overrides",
    comment: "Comment",
    sound: "Sound",
    icon: "Icon",
    beam: "Beam",
    text: "Text",
    border: "Border",
    background: "Background",
    transparency: "Transparency",
    coast: "Coast",
    forest: "Forest",
    sand: "Sand",
    volume: "Volume",
    soundType: "Sound Type",
    default: "Default",
    sharket: "Sharket",
    custom: "Custom",
    filePath: "File Path",
    test: "Test",
    search: "Search...",
    size: "Size",
    shape: "Shape",
    temporary: "Temporary",
    small: "Small",
    medium: "Medium",
    large: "Large",
    small_sh: "S",
    medium_sh: "M",
    large_sh: "L",
    copy: "Copy",
    paste: "Paste",
    cancel: "Cancel",
    ok: "OK",
    none: "None",
    permanent: "Permanent",
    viewerSettings: "Viewer Settings",
    copyText: "Copy Text",
    bulkEdit: "Bulk Edit",
    addNewTier: "Add New Tier",
    testSound: "Test Sound",
    color: "Color",
    name: "Name",
    source: "Source",
    targetTooltip: "Targets are optional. If empty, the rule applies to all items in this tier. Use targets to apply specific conditions or style overrides to individual items within the tier.",
    quickRules: "Quick Add Rules",
    addCustomRule: "Add Custom Rule (Raw)",
    stackSizeRule: "Stack Size Rule",
    gemLevelRule: "Gem Level Rule",
    qualityRule: "High Quality Rule",
    influenceRule: "Influenced Rule",
    fracturedRule: "Fractured Rule",
    socketRule: "Sockets/Links Rule",
    itemLevelRule: "High ItemLevel Rule",
    Red: "Red",
    Green: "Green",
    Blue: "Blue",
    Brown: "Brown",
    White: "White",
    Yellow: "Yellow",
    Cyan: "Cyan",
    Grey: "Grey",
    Orange: "Orange",
    Pink: "Pink",
    Purple: "Purple",
    Temp: "Temp",
    dragToReorder: "Drag to reorder",
    insertTierBefore: "Insert Tier Before",
    insertTierAfter: "Insert Tier After",
    above: "ABOVE",
    below: "BELOW",
    copyTier: "Copy Tier",
    deleteTier: "Delete Tier",
    insertBefore: "Insert Before",
    insertAfter: "Insert After",
    pasteTier: "Paste Tier",
    confirmDeleteTier: "Are you sure you want to delete this tier?",
    DRAG:"DRAG",
    untiered: "Untiered",
    itemsStaged: "items staged",
    activeTierBrush: "Active Tier (Brush):",
    saveChanges: "Save Changes",
    itemClass: "Item Class",
    itemSubType: "Item SubType",
    requiresLevel: "Requires Level",
    actions: "Actions",
    deleteRuleConfirm: "Are you sure you want to delete this rule?",
    ruleComment: "Rule Comment...",
    addItemTarget: "Add item target...",
    themeOverrides: "Theme Overrides",
    moveTo: "Move to:",
    enableRule: "Enable Rule",
    disableRule: "Disable Rule",
    goToRule: "Go to Rule",
    removeFromRule: "Remove from Rule",
    deleteRuleLabel: "Delete Rule",
    rangeBetween: "Between",
    t0MoveWarning: "You are moving a Top Tier item ({name}) into a HIDE tier. Are you sure?",
    t0OrderWarning: "You are moving a custom tier above Tier 0. This is usually not recommended. Continue?",
    t0InsertWarning: "You are inserting a new tier above Tier 0. Continue?",
    copyLabel: "(Copy)",
    str: "Str",
    dex: "Dex",
    int: "Int",
    dropLevel: "Drop Level",
    physicalDamage: "Physical Damage",
    criticalStrikeChance: "Critical Strike Chance",
    attacksPerSecond: "Attacks per Second",
    Stackable_Currency: "Stackable Currency",
    Body_Armours: "Body Armours",
    Boots: "Boots",
    Gloves: "Gloves",
    Helmets: "Helmets",
    Shields: "Shields",
    One_Hand_Axes: "One Hand Axes",
    One_Hand_Maces: "One Hand Maces",
    One_Hand_Swords: "One Hand Swords",
    Sceptres: "Sceptres",
    Staves: "Staves",
    Warstaves: "Warstaves",
    Two_Hand_Axes: "Two Hand Axes",
    Two_Hand_Maces: "Two Hand Maces",
    Two_Hand_Swords: "Two Hand Swords",
    Wands: "Wands",
    Active_Skill_Gems: "Active Skill Gems",
    Support_Skill_Gems: "Support Skill Gems",
    Maps: "Maps",
    Map_Fragments: "Map Fragments",
    Divination_Card: "Divination Card",
    Amulets: "Amulets",
    Rings: "Rings",
    Belts: "Belts",
    Bows: "Bows",
    Claws: "Claws",
    Daggers: "Daggers",
    Rune_Daggers: "Rune Daggers",
    Quivers: "Quivers",
    All: "All",
    Armour: "Armour",
    Evasion_Rating: "Evasion Rating",
    Energy_Shield: "Energy Shield",
    Armour_ES: "Armour/ES",
    Evasion_Armour: "Evasion/Armour",
    ES_Evasion: "ES/Evasion",
    Armour_Evasion_ES: "Armour/Evasion/ES",
  },
  ch: {
    appTitle: "POE 过滤器编辑器",
    editor: "编辑器",
    simulator: "模拟器",
    saveExport: "保存与导出",
    saveConfig: "保存配置",
    generateFilter: "生成过滤器",
    selectFile: "从左侧选择文件以编辑",
    itemsInTier: "此阶级物品",
    noItems: "此阶级无物品",
    searchPlaceholder: "搜索以添加物品...",
    filterPlaceholder: "筛选当前物品...",
    fontSize: "字体大小",
    textColor: "文本颜色",
    borderColor: "边框颜色",
    bgColor: "背景颜色",
    itemPreview: "物品预览",
    dropSimulator: "掉落模拟器",
    visual: "可视化",
    rawText: "原始文本",
    clearGround: "清空地面",
    refreshStyles: "刷新样式",
    typeToDrop: "输入物品名称以落...",
    groundEmpty: "地面为空。添加一些掉落物吧~",
    loading: "加载中...",
    generating: "生成中...",
    generatedSuccess: "过滤器生成成功！",
    saveSuccess: "保存成功！",
    moveFailed: "移动物品失败",
    loadFailed: "加载失败",
    inspector: "检查员",
    rawFilter: "原始过滤器代码",
    styleClipboard: "样式剪贴板",
    copyStyle: "复制样式",
    pasteStyle: "粘贴样式",
    clearClipboard: "清空",
    visibility: "可见性",
    show: "显示",
    hide: "隐藏",
    gameVersion: "游戏版本",
    gameMode: "游戏模式",
    normalMode: "普通",
    ruthlessMode: "无情",
    rules: "规则",
    addRule: "添加规则",
    deleteRule: "删除规则",
    targets: "目标",
    conditions: "条件",
    overrides: "覆盖设定",
    comment: "备注",
    sound: "声音",
    icon: "图标",
    beam: "光柱",
    text: "文本",
    border: "边框",
    background: "背景",
    transparency: "透明度",
    coast: "海滩",
    forest: "丛林",
    sand: "沙漠",
    volume: "音量",
    soundType: "声音类型",
    default: "系统默认",
    sharket: "Sharket音效",
    custom: "自定义路径",
    filePath: "文件路径",
    test: "测试",
    search: "搜索...",
    size: "大小",
    shape: "形状",
    temporary: "临时",
    small: "小",
    medium: "中",
    large: "大",
    small_sh: "小",
    medium_sh: "中",
    large_sh: "大",
    copy: "复制",
    paste: "粘贴",
    cancel: "取消",
    ok: "确定",
    none: "无",
    permanent: "永久",
    viewerSettings: "显示设置",
    copyText: "复制文本",
    bulkEdit: "批量编辑",
    addNewTier: "添加新阶级",
    testSound: "测试音效",
    color: "颜色",
    name: "名称",
    source: "来源",
    targetTooltip: "目标是可选的。如果为空，则该规则应用于此阶级中的所有物品。使用目标可以对阶级内的单个物品应用特定条件或样式覆盖。",
    quickRules: "快速添加规则",
    addCustomRule: "添加自定义规则 (原始代码)",
    stackSizeRule: "堆叠数量规则",
    gemLevelRule: "宝石等级规则",
    qualityRule: "高品质规则",
    influenceRule: "势力物品规则",
    fracturedRule: "破碎物品规则",
    socketRule: "插槽/连线规则",
    itemLevelRule: "高物等规则",
    Red: "红色",
    Green: "绿色",
    Blue: "蓝色",
    Brown: "棕色",
    White: "白色",
    Yellow: "黄色",
    Cyan: "青色",
    Grey: "灰色",
    Orange: "橙色",
    Pink: "粉色",
    Purple: "紫色",
    Temp: "临时",
    dragToReorder: "拖动排序",
    insertTierBefore: "在此之前插入新阶级",
    insertTierAfter: "在此之后插入新阶级",
    above: "上方",
    below: "下方",
    copyTier: "复制阶级",
    deleteTier: "删除阶级",
    insertBefore: "在此之前插入",
    insertAfter: "在此之后插入",
    pasteTier: "粘贴阶级",
    confirmDeleteTier: "确定要删除此阶级吗?",
    DRAG:"拖动",
    untiered: "未分类",
    itemsStaged: "项变动",
    activeTierBrush: "当前阶级 (刷子):",
    saveChanges: "保存更改",
    itemClass: "物品类型",
    itemSubType: "物品子类型",
    requiresLevel: "等级需求",
    actions: "操作",
    deleteRuleConfirm: "确定要删除此规则吗？",
    ruleComment: "规则备注...",
    addItemTarget: "添加物品目标...",
    themeOverrides: "外观覆盖",
    moveTo: "移动至:",
    enableRule: "启用规则",
    disableRule: "禁用规则",
    goToRule: "跳转至规则",
    removeFromRule: "从规则中移除",
    deleteRuleLabel: "删除规则",
    rangeBetween: "范围",
    t0MoveWarning: "你正在将顶级物品({name})移入隐藏分类，确定吗？",
    t0OrderWarning: "你正在将自定义阶级移至 T0 之上，这通常不被推荐。确定吗？",
    t0InsertWarning: "你正在 T0 之上插入新阶级。确定吗？",
    copyLabel: "(副本)",
    str: "力量",
    dex: "敏捷",
    int: "智慧",
    dropLevel: "掉落等级",
    physicalDamage: "物理伤害",
    criticalStrikeChance: "暴击率",
    attacksPerSecond: "每秒攻击次数",
    Stackable_Currency: "可堆叠通货",
    Body_Armours: "胸甲",
    Boots: "鞋子",
    Gloves: "手套",
    Helmets: "头部",
    Shields: "盾",
    One_Hand_Axes: "单手斧",
    One_Hand_Maces: "单手锤",
    One_Hand_Swords: "单手剑",
    Sceptres: "短杖",
    Staves: "长杖",
    Warstaves: "战杖",
    Two_Hand_Axes: "双手斧",
    Two_Hand_Maces: "双手锤",
    Two_Hand_Swords: "双手剑",
    Wands: "法杖",
    Active_Skill_Gems: "技能宝石",
    Support_Skill_Gems: "辅助宝石",
    Maps: "地图",
    Map_Fragments: "碎片",
    Divination_Card: "命运卡",
    Amulets: "项链",
    Rings: "戒指",
    Belts: "腰带",
    Bows: "弓",
    Claws: "爪",
    Daggers: "匕首",
    Rune_Daggers: "符文匕首",
    Quivers: "箭袋",
    All: "全部",
    Armour: "护甲",
    Evasion_Rating: "闪避",
    Energy_Shield: "能量护盾",
    Armour_ES: "护甲/能量护盾",
    Evasion_Armour: "闪避/护甲",
    ES_Evasion: "能量护盾/闪避",
    Armour_Evasion_ES: "护甲/能量护盾/闪避",
  }
};

export const useTranslation = (lang: Language) => {
  return translations[lang];
};

export const getItemName = (item: { name: string; name_ch?: string }, lang: Language) => {
  if (lang === 'ch' && item.name_ch) return item.name_ch;
  return item.name;
};